name: External Buildkite
description: Download Buildkite configuration files from an external repository
author: https://github.com/JuliaCI
requirements: [git]
configuration:
  properties:
    external_repo:
      type: string
    folder:
      type: string
    this_is_first_job:
      type: boolean
    version:
      type: string
    version_file:
      type: string
  additionalProperties: false
  required:
    - external_repo
    - folder
