name: External Buildkite
description: Download Buildkite configuration files from an external repository
author: https://github.com/JuliaCI
requirements: [git]
configuration:
  properties:
    # The external repository that we will clone.
    # Example value: https://github.com/JuliaCI/julia-buildkite
    repo_url:
      type: string

    # Folder the external repository will be cloned into
    # defaults to `.buildkite`
    folder:
      type: string

    # The version of the external repository that will be cloned
    # This can be a gitsha, a gitref, or a path to a file that contains
    # within it a gitsha or gitref.
    version:
      type: string
  additionalProperties: false
  required:
    - repo_url
    - folder
