#!/bin/bash

set -Eeuo pipefail

echo "--- Print the \`external-buildkite\` plugin inputs:"

BK_VERSION_FILE="${BUILDKITE_PLUGIN_EXTERNAL_BUILDKITE_VERSION_FILE:?}"
BK_EXTERNAL_REPO="${BUILDKITE_PLUGIN_EXTERNAL_BUILDKITE_EXTERNAL_REPO:?}"
BK_FOLDER_NAME="${BUILDKITE_PLUGIN_EXTERNAL_BUILDKITE_FOLDER:?}"

echo "The Buildkite config version is located in the following file: ${BK_VERSION_FILE:?}"
echo "The Buildkite config files will be downloaded from the following repository: ${BK_EXTERNAL_REPO:?}"
echo "The Buildkite config files will be downloaded into the following folder: ${BK_FOLDER_NAME:?}"

echo "--- Print the commit in the primary repository"
# Note: we allow this command to fail.
git log -n 1 || echo "WARNING: could not successfully run the \"git log -n 1\" command"

echo "--- Print the Buildkite config version"

BK_VERSION_NLINES=$(wc -l ${BK_VERSION_FILE:?} | awk '{ print $1 }')
BK_VERSION_NWORDS=$(wc -w ${BK_VERSION_FILE:?} | awk '{ print $1 }')

if [ "${BK_VERSION_NLINES:?}" != "1" ]; then
  echo "ERROR: The ${BK_VERSION_FILE:?} file contains ${BK_VERSION_NLINES:?} lines."
  echo "ERROR: It is only supposed to contain 1 line."
  exit 1
fi

if [ "${BK_VERSION_NWORDS:?}" != "1" ]; then
  echo "ERROR: The ${BK_VERSION_FILE:?} file contains ${BK_VERSION_NWORDS:?} words."
  echo "ERROR: It is only supposed to contain 1 word."
  exit 1
fi

BK_VERSION_VALUE=$(cat ${BK_VERSION_FILE:?} | tr -s ' ')

echo "The Buildkite config version is: ${BK_VERSION_VALUE:?}"

echo "--- Clone from ${BK_EXTERNAL_REPO:?}"

rm -rf ${BK_FOLDER_NAME:?}
git clone ${BK_EXTERNAL_REPO:?} ${BK_FOLDER_NAME:?}
cd ${BK_FOLDER_NAME:?}

echo "--- Check out ${BK_VERSION_VALUE:?}"
git checkout ${BK_VERSION_VALUE:?}

echo "--- Print the commit in the external repository"
git log -n 1

cd ..
